name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"  # Adjust the Node.js version if needed

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> ${{ runner.temp }}/output.txt
            echo "command=install" >> ${{ runner.temp }}/output.txt
            echo "runner=yarn" >> ${{ runner.temp }}/output.txt
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> ${{ runner.temp }}/output.txt
            echo "command=ci" >> ${{ runner.temp }}/output.txt
            echo "runner=npx --no-install" >> ${{ runner.temp }}/output.txt
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Install Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} npm install next react react-dom

      - name: Build with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build

      - name: Verify build output
        run: ls -l ./.next  # Verify if the .next directory exists and contains build output

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: ./.next  # Upload the .next directory as an artifact

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: nextjs-build  # Use the correct artifact name here
          path: ./.next  # Download the .next directory artifact

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "manaspasayat3@gmail.com"
          git config --global user.name "Manas Pasayat"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r ./.next/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -M gh-pages
          git push -f origin gh-pages
